// This file was generated by counterfeiter
package vmoptionsfakes

import (
	"sync"

	"github.com/cloudfoundry/java-buildpack-memory-calculator/memory"
)

type FakeVmOptions struct {
	StringStub        func() string
	stringMutex       sync.RWMutex
	stringArgsForCall []struct{}
	stringReturns     struct {
		result1 string
	}
	MemOptStub        func(memoryType memory.MemoryType) memory.MemSize
	memOptMutex       sync.RWMutex
	memOptArgsForCall []struct {
		memoryType memory.MemoryType
	}
	memOptReturns struct {
		result1 memory.MemSize
	}
	SetMemOptStub        func(memoryType memory.MemoryType, size memory.MemSize)
	setMemOptMutex       sync.RWMutex
	setMemOptArgsForCall []struct {
		memoryType memory.MemoryType
		size       memory.MemSize
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeVmOptions) String() string {
	fake.stringMutex.Lock()
	fake.stringArgsForCall = append(fake.stringArgsForCall, struct{}{})
	fake.recordInvocation("String", []interface{}{})
	fake.stringMutex.Unlock()
	if fake.StringStub != nil {
		return fake.StringStub()
	} else {
		return fake.stringReturns.result1
	}
}

func (fake *FakeVmOptions) StringCallCount() int {
	fake.stringMutex.RLock()
	defer fake.stringMutex.RUnlock()
	return len(fake.stringArgsForCall)
}

func (fake *FakeVmOptions) StringReturns(result1 string) {
	fake.StringStub = nil
	fake.stringReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeVmOptions) MemOpt(memoryType memory.MemoryType) memory.MemSize {
	fake.memOptMutex.Lock()
	fake.memOptArgsForCall = append(fake.memOptArgsForCall, struct {
		memoryType memory.MemoryType
	}{memoryType})
	fake.recordInvocation("MemOpt", []interface{}{memoryType})
	fake.memOptMutex.Unlock()
	if fake.MemOptStub != nil {
		return fake.MemOptStub(memoryType)
	} else {
		return fake.memOptReturns.result1
	}
}

func (fake *FakeVmOptions) MemOptCallCount() int {
	fake.memOptMutex.RLock()
	defer fake.memOptMutex.RUnlock()
	return len(fake.memOptArgsForCall)
}

func (fake *FakeVmOptions) MemOptArgsForCall(i int) memory.MemoryType {
	fake.memOptMutex.RLock()
	defer fake.memOptMutex.RUnlock()
	return fake.memOptArgsForCall[i].memoryType
}

func (fake *FakeVmOptions) MemOptReturns(result1 memory.MemSize) {
	fake.MemOptStub = nil
	fake.memOptReturns = struct {
		result1 memory.MemSize
	}{result1}
}

func (fake *FakeVmOptions) SetMemOpt(memoryType memory.MemoryType, size memory.MemSize) {
	fake.setMemOptMutex.Lock()
	fake.setMemOptArgsForCall = append(fake.setMemOptArgsForCall, struct {
		memoryType memory.MemoryType
		size       memory.MemSize
	}{memoryType, size})
	fake.recordInvocation("SetMemOpt", []interface{}{memoryType, size})
	fake.setMemOptMutex.Unlock()
	if fake.SetMemOptStub != nil {
		fake.SetMemOptStub(memoryType, size)
	}
}

func (fake *FakeVmOptions) SetMemOptCallCount() int {
	fake.setMemOptMutex.RLock()
	defer fake.setMemOptMutex.RUnlock()
	return len(fake.setMemOptArgsForCall)
}

func (fake *FakeVmOptions) SetMemOptArgsForCall(i int) (memory.MemoryType, memory.MemSize) {
	fake.setMemOptMutex.RLock()
	defer fake.setMemOptMutex.RUnlock()
	return fake.setMemOptArgsForCall[i].memoryType, fake.setMemOptArgsForCall[i].size
}

func (fake *FakeVmOptions) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.stringMutex.RLock()
	defer fake.stringMutex.RUnlock()
	fake.memOptMutex.RLock()
	defer fake.memOptMutex.RUnlock()
	fake.setMemOptMutex.RLock()
	defer fake.setMemOptMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeVmOptions) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ memory.VmOptions = new(FakeVmOptions)
