---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfje/java-buildpack-memory-calculator
    tag: latest

inputs:
- name: java-buildpack-memory-calculator
  path: gopath/cloudfoundry/java-buildpack-memory-calculator

run:
  path: gopath/cloudfoundry/java-buildpack-memory-calculator/ci/build.sh

params:
  ARTIFACTORY_REPOSITORY: libs-snapshot-local
  VERSION:                3.14.0.BUILD-SNAPSHOT

  ARTIFACTORY_USERNAME:
  ARTIFACTORY_PASSWORD:
