---

var:
  memory-calculator-repository: &memory-calculator-repository-config
    uri: https://github.com/instana/java-buildpack-memory-calculator.git
    username: ((project-berlin-gh-token))
    password: x-oauth-basic
    branch: ((branch))
    git_config:
      - name: user.name
        value: Stan
      - name: user.email
        value: stan@instana.com

resources:
  - name: java-buildpack-memory-calculator
    type: git
    icon: github
    source:
      <<: *memory-calculator-repository-config

jobs:
  - name: self-update
    max_in_flight: 1
    plan:
      - get: java-buildpack-memory-calculator
        trigger: true
      - task: render-pipeline-template
        # see notes in the task file about why we need to copy-paste this task.
        file: java-buildpack-memory-calculator/ci/render-template-task.yml
        input_mapping:
          repo: java-buildpack-memory-calculator
        vars:
          template: ci/pipeline.yml  # this path has to be relative to 'repo'
          branch: ((branch))
      - set_pipeline: self
        file: rendered/pipeline.yml
        vars:
          branch: ((branch))
          project-berlin-gh-token: ((project-berlin-gh-token))
          delivery-instana-io-release-project-artifact-read-writer-creds: ((delivery-instana-io-release-project-artifact-read-writer-creds))

  - name: test-and-build-and-deploy-only-on-main
    max_in_flight: 1
    plan:
      - get: java-buildpack-memory-calculator
        trigger: true
        passed: [ self-update ]
      - task: tests
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: registry.access.redhat.com/ubi8/go-toolset
              tag: 1.17
          inputs:
            - name: java-buildpack-memory-calculator
          run:
            path: java-buildpack-memory-calculator/ci/unit-test.sh
      - task: build
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: registry.access.redhat.com/ubi8/ubi-minimal
          inputs:
            - name: java-buildpack-memory-calculator
          outputs:
            - name: builds
          params:
            SOURCE_DIR: java-buildpack-memory-calculator
            TARGET_DIR: builds
          run:
            path: /bin/bash
            args:
              - -exc
              - |
                microdnf -y install tar gzip wget make findutils
                
                # install newest go version
                export GO_VERSION="1.20.7"
                export GO_SHAR256="f0a87f1bcae91c4b69f8dc2bc6d7e6bfcd7524fceec130af525058c0c17b1b44 go${GO_VERSION}.linux-amd64.tar.gz"
                export GO_BINARY="go${GO_VERSION}.linux-amd64.tar.gz"
                wget "https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz"
                echo "${GO_SHAR256}" | sha256sum --check
                gunzip "${GO_BINARY}"
                tar xf "${GO_BINARY//.gz/}"
                mv go /usr/local/bin
                export PATH=$PATH:/usr/local/bin/go/bin/
                export SOURCE_DIR="$(pwd)/${SOURCE_DIR}"
                export TARGET_DIR="$(pwd)/${TARGET_DIR}"
                bash -x ${SOURCE_DIR}/ci/package.sh
      - load_var: version
        file: java-buildpack-memory-calculator/VERSION
        reveal: true
      - task: deploy_to_artifactory
        yx_if:
          - eq: [((branch)), main]
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: maven
          inputs:
            - name: java-buildpack-memory-calculator
            - name: builds
          params:
            VERSION: ((.:version))
            DELIVERY_ARTIFACTORY_GENERIC_BASE_URL: ((delivery-artifactory-generic-agent-release-url))
            DELIVERY_ARTIFACTORY_USERNAME: ((delivery-instana-io-release-project-artifact-read-writer-creds.username))
            DELIVERY_ARTIFACTORY_PASSWORD: ((delivery-instana-io-release-project-artifact-read-writer-creds.password))
          run:
            path: bash
            args:
              - -c
              - |
                set -e
                
                regex='memory-calculator_(.+)'
                for filename in builds/memory-calculator_*; do
                  [[ $(basename "${filename}") =~ ${regex} ]] && \
                    bash -x java-buildpack-memory-calculator/ci/deploy_to_artifactory.sh "${filename}" "${BASH_REMATCH[1]}" "${VERSION}"
                done
